trigger:
  branches:
    include:
      - main

stages:
- stage: Build
  displayName: 'Build Stage'
  jobs:
    - job: Build
      pool:
        vmImage: 'ubuntu-latest'
      steps:
        - task: Maven@3
          inputs:
            mavenPomFile: 'pom.xml'
            goals: 'clean package'
            mavenOptions: '-Xmx1g'
            javaHomeOption: 'JDKVersion'
            jdkVersionOption: '1.17'

        - script: |
            echo "Building Docker image..."
            docker build -t freelance-app .
            docker images
          displayName: 'Build Docker Image'

- stage: Test
  displayName: 'Test Stage'
  dependsOn: Build
  jobs:
    - job: Test
      pool:
        vmImage: 'ubuntu-latest'
      steps:
        - task: Maven@3
          inputs:
            mavenPomFile: 'pom.xml'
            goals: 'test'
            javaHomeOption: 'JDKVersion'
            jdkVersionOption: '1.17'

- stage: Deploy
  displayName: 'Deploy Stage'
  dependsOn: Test
  condition: succeeded()
  jobs:
    - job: Deploy
      pool:
        vmImage: 'ubuntu-latest'
      steps:
        - task: AzureWebAppContainer@1
          inputs:
            azureSubscription: '<your-azure-service-connection>'
            appName: 'freelance-java-app'
            containers: 'freelance-app'
