server:
  port: 8081

spring:
  application:
    name: job-service
  datasource:
    url: jdbc:sqlserver://<your-server>.database.windows.net:1433;database=<your-db>
    username: <your-username>
    password: <your-password>
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
