trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

stages:
- stage: Build
  jobs:
  - job: Build
    steps:
    - task: Maven@3
      inputs:
        mavenPomFile: 'pom.xml'
        goals: 'package'
        publishJUnitResults: true

- stage: Test
  dependsOn: Build
  jobs:
  - job: Test
    steps:
    - script: echo "Run tests here (if configured)"
      displayName: 'Run Tests'

- stage: Deploy
  dependsOn: Test
  jobs:
  - job: Deploy
    steps:
    - script: echo "Deploy to Azure Web App or AKS here"
      displayName: 'Deploy Step'